In [ ]:
# Brittany Toy 
# OCNG 489
# HW 3

In [2]:
#1 Vector Manipulation 
import numpy as np
a = np.zeros(10)
a[4] = 1
print (a)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [21]:
#2 Vector Range
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
#3 Reverse Vector
def reverse(a):
    return a[::-1]
reverse(a)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [4]:
#4 Find indices of non-zero elements 
def find_nonzero(ap):
    return np.nonzero(ap)
ap = np.array([1,2,0,0,4,0])
find_nonzero(ap)
ap[find_nonzero(ap)]

array([1, 2, 4])

In [7]:
#5 Array with random values
M = np.random.normal(0,1,(3,3,3))
M

array([[[-0.32507333,  0.49994333,  1.04481869],
        [ 0.41721879,  1.25126945, -0.72575781],
        [ 0.62721207, -1.26254434,  0.56955997]],

       [[-0.1065434 ,  0.72746738, -0.70275281],
        [-0.02943265,  0.86390049, -0.9378579 ],
        [ 1.90450606, -0.12020118,  0.40148085]],

       [[-1.83171338,  0.82075204,  1.05384895],
        [-0.97046528, -0.38255387,  0.50649119],
        [-0.61366659, -0.83219322,  1.04264911]]])

In [13]:
#6 Operations on an array with random values
N = np.random.random((10,10))
print(N)
Nmin = np.min(N[:,3])
Nmax = np.max(N[1,:])
print(Nmin,Nmax)

[[ 0.28870012  0.58108433  0.33750819  0.25538434  0.32269328  0.31424609
   0.17283519  0.37137725  0.93524483  0.58105489]
 [ 0.08038587  0.02429819  0.91359305  0.36561426  0.49639543  0.14417165
   0.781185    0.66417001  0.83336811  0.58356787]
 [ 0.20055148  0.77362721  0.4862852   0.69698683  0.25674369  0.77154188
   0.50259379  0.24851767  0.38261965  0.08569006]
 [ 0.45007765  0.53029814  0.98690059  0.28897379  0.39514318  0.86123315
   0.81292956  0.75270663  0.42707899  0.55037726]
 [ 0.80259487  0.07267742  0.62753012  0.066933    0.1188031   0.17099634
   0.3428773   0.28291642  0.56417697  0.92759824]
 [ 0.34477908  0.55112752  0.76004152  0.06152267  0.07310254  0.91751438
   0.9989773   0.71389889  0.71281545  0.50780458]
 [ 0.49094098  0.13137719  0.39242198  0.27391063  0.12234055  0.14421848
   0.76078431  0.62482259  0.51243703  0.38445404]
 [ 0.24467134  0.08010301  0.19088834  0.03843793  0.81233552  0.69359143
   0.53551801  0.90605176  0.22429521  0.54136572]


In [8]:
#7 Vectors without end points 
G = np.linspace(0,1,12,endpoint=True)[1:-1]
print(G)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [9]:
#8 Sorted vector
R = np.random.random(10)
R.sort()
print(R)

[ 0.03151444  0.18022673  0.20998668  0.33687334  0.44133543  0.55906477
  0.65880533  0.77277659  0.86176105  0.91999185]


In [7]:
#9 Test for array equality 
def is_equal(A,B): 
    return A==B
A = np.array([6,5])
B = np.array([6,5])

print(is_equal(A,B))

[ True  True]


In [9]:
#10 Subtract the row mean from rows of a matrix
C = np.random.rand(5,10)
Q = C - C.mean(axis=1, keepdims=True)

print(Q)

[[ 0.03894945 -0.11552459 -0.26087021  0.12661452  0.13391773 -0.0537429
   0.06782137 -0.30865695 -0.00098393  0.37247551]
 [ 0.27728608  0.11217925  0.20420044  0.05996276 -0.07093536 -0.50359303
   0.17245742  0.18639467 -0.05846577 -0.37948645]
 [ 0.32550031  0.05818582  0.07593896  0.17566009  0.05368995 -0.33373821
  -0.40961444 -0.36012497  0.15042914  0.26407336]
 [-0.37355929 -0.27567808 -0.36893016  0.22429599  0.30523895  0.46318548
  -0.02220463  0.32617739 -0.27922411  0.00069846]
 [ 0.12637809 -0.22014852 -0.00703469  0.50121822  0.14803651 -0.26249139
  -0.30808694 -0.09087478  0.46370427 -0.35070078]]


In [13]:
#11 Multiply arrays
#Part A Multiplying (5,5,3) by (5,5)
W = np.ones((5,5,3))
I = 8*np.ones((5,5))
print(W * I[:,:,None])

[[[ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]]

 [[ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]]

 [[ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]]

 [[ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]]

 [[ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]
  [ 8.  8.  8.]]]


In [12]:
#11 Multiply arrays
#Part B Multiplying (3,5,5) by (5,5)
Y = np.ones((3,5,5))
I = 8*np.ones((5,5))
print (Y * I)

[[[ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]]

 [[ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]]

 [[ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]
  [ 8.  8.  8.  8.  8.]]]


In [66]:
#12 Creating a new array
Z = np.arange(1,15)
q = []
for n in Z: 
    if n < 12:
        p = np.array([n, n + 1, n + 2, n + 3])
        q.append([p])
        R = np.asarray(q)
    elif n == 12 or n == 13:  
        continue
    else:
        print(R)


[[[ 1  2  3  4]]

 [[ 2  3  4  5]]

 [[ 3  4  5  6]]

 [[ 4  5  6  7]]

 [[ 5  6  7  8]]

 [[ 6  7  8  9]]

 [[ 7  8  9 10]]

 [[ 8  9 10 11]]

 [[ 9 10 11 12]]

 [[10 11 12 13]]

 [[11 12 13 14]]]


In [64]:
#13 Convert from Cartesian to polar coordinates
def cart2polar(xy): 
    x = xy[:,0] 
    y = xy[:,1]
    r = np.sqrt(x**2 + y**2)
    p = np.arctan2(y,x)
    return np.transpose(np.array([r,p]))

f = np.array([[6,2],[7,8]])
f

array([[6, 2],
       [7, 8]])

In [ ]:
#14 Compute and time for loops and array operations
import time 
a = np.arange(1024.0).reshape(4, 8, 16, 2)
b = np.random.rand(4, 8, 16, 2)
%timeit sol = a * b 


In [37]:
#15 Fix the code 
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]/4  #Added /4 and deleted the next line
    a[:2, :] -= aa   
    bb=b[:,None]     #Added bb equals to b[:,None]
    return a*bb #Changed a to ac and added [:,None]
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)
print(res)
assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

[[ 2.25  2.25]
 [ 2.25  2.25]
 [ 3.    3.  ]]


In [70]:
#16 Calculate components of a vector
data = np.loadtxt('burl1h2010.txt')
vdir = data[:,5]
vspd = data[:,6]
def winds(vdir, vspd):
    d = np.radians(vdir)
    u = (vspd)*np.cos(d)
    v = (vspd)*np.sin(d)
    return (u,v)
